name: dart-sass
title: Dart Sass
version: '1.97.1'
summary: Transpile Sass to CSS
description: |
  Dart Sass is the reference implementation of Sass, written in Dart.

  Sass is a style sheet language that is transpiled to CSS. It allows you to
  use variables, nested rules, mixins, functions, and more, all with a fully
  CSS-compatible syntax. Sass helps keep large style sheets well-organized and
  makes it easy to share design within and across projects.

  To transpile Sass to CSS:
  `dart-sass in.scss out.css`

  To create an alias from `sass` to `dart-sass`:
  `sudo snap alias dart-sass sass`

  To remove the alias:
  `sudo snap unalias sass`

  References:
  * Documentation: https://sass-lang.com
  * Project: https://github.com/sass/dart-sass

# Administrative Metadata
license: MIT
icon: snap/local/logo.png
contact: https://github.com/jmooring/dart-sass-snap
website: https://github.com/sass/dart-sass
issues: https://github.com/jmooring/dart-sass-snap/issues
donation: https://github.com/sponsors/jmooring
source-code: https://github.com/jmooring/dart-sass-snap

# Build Configuration
base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  dart-sass:
    command: sass
    plugs:
      - home

parts:
  binary:
    plugin: dump
    source:
      - on amd64: https://github.com/sass/dart-sass/releases/download/1.97.1/dart-sass-1.97.1-linux-x64.tar.gz
      - on arm64: https://github.com/sass/dart-sass/releases/download/1.97.1/dart-sass-1.97.1-linux-arm64.tar.gz
